/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SrDslUiModule extends AbstractSrDslUiModule {

	public SrDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
