<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="studyprogramme" nsURI="platform:/plugin/tdt4250.studyprogramme.model/model/studyprogramme.ecore"
    nsPrefix="studyprogramme">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="validationDelegates" value="http://www.eclipse.org/acceleo/query/1.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="UOD">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="programmesMustHaveUniqueCode"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="programmesMustHaveUniqueCode" value="self.programmes->isUnique( p | p.code)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="programmes" upperBound="-1"
        eType="#//Programme" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Code" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseCriterion" upperBound="-1"
        eType="#//CourseCriterion" eOpposite="#//CourseCriterion/courses"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//CourseLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//Code"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseLevel">
    <eLiterals name="basicCourses"/>
    <eLiterals name="advancedCourses" value="1"/>
    <eLiterals name="postgraduateLevel" value="2"/>
    <eLiterals name="doctoralLevel" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Programme">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="#//Code"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fullName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="academicYears" upperBound="-1"
        eType="#//AcademicYear" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisations" upperBound="-1"
        eType="#//Specialisation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creditsRequirement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcademicYear">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="hasEnoughCredits"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromYear" eType="#//Year"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromSeason" eType="#//Season"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseCombinations" upperBound="-1"
        eType="#//CourseCombination" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Season">
    <eLiterals name="spring"/>
    <eLiterals name="autumn" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseCombination">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="containsEitherCourseCombinationsOrCourseGroups"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/acceleo/query/1.0">
      <details key="containsEitherCourseCombinationsOrCourseGroups" value="if self.courseGroups->size() > 0 and self.courseCombinations->size() > 0 then false else true endif"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialisation" eType="#//Specialisation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creditsRequirement" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromTerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseCombinations" upperBound="-1"
        eType="#//CourseCombination" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courseGroups" upperBound="-1"
        eType="#//CourseGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Specialisation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="specialisation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseGroup">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="minimumOneCoursePresent"/>
    </eAnnotations>
    <eOperations name="getCourses" upperBound="-1" eType="#//Course"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fromTerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="toTerm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" upperBound="-1"
        eType="#//Criterion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//CourseStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredCredits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CourseStatus">
    <eLiterals name="mandatory"/>
    <eLiterals name="elective" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Criterion" abstract="true">
    <eOperations name="filterCourses" upperBound="-1" eType="#//Course">
      <eParameters name="courses" upperBound="-1" eType="#//Course"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="criteria" upperBound="-1"
        eType="#//Criterion" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseCriterion" eSuperTypes="#//Criterion">
    <eOperations name="filterCourses" upperBound="-1" eType="#//Course">
      <eParameters name="courses" upperBound="-1" eType="#//Course"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" upperBound="-1"
        eType="#//Course" eOpposite="#//Course/courseCriterion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseLevelCriterion" eSuperTypes="#//Criterion">
    <eOperations name="filterCourses" upperBound="-1" eType="#//Course">
      <eParameters name="courses" upperBound="-1" eType="#//Course"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="courseLevel" eType="#//CourseLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Year" instanceClassName="int"/>
</ecore:EPackage>
