<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="timetable" nsURI="http://www.example.org/timetable" nsPrefix="timetable">
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campus" lowerBound="1"
        upperBound="-1" eType="#//Campus" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        upperBound="-1" eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacher" lowerBound="1"
        upperBound="-1" eType="#//Teacher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2024"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ACourseCannotHaveTwoTimetablesForTheSameWeek"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinator" lowerBound="1"
        eType="#//Teacher"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturer" upperBound="-1"
        eType="#//Teacher"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coursetimetable" lowerBound="1"
        eType="#//CourseTimetable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Teacher">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="ATeacherCannotAppearInTwoRoomsAtTheSameTime"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1" upperBound="-1"
        eType="#//Slot" eOpposite="#//Slot/lecturer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Campus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="building" lowerBound="1"
        upperBound="-1" eType="#//Building" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Building">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" upperBound="-1" eType="#//Room"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="TwoCoursesCannotBeScheduledInTheSameRoomAtTheSameTime"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mazemapLink" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" upperBound="-1" eType="#//Slot"
        eOpposite="#//Slot/room"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Week">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WeekNumberMustBeBetween1And52"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="slot" lowerBound="1" upperBound="-1"
        eType="#//Slot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Slot">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="TheTeacherMustBeTheCourseCoordinatorOrALecturer StartAndEndTimesAreIncorrect"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="day" lowerBound="1" eType="#//DayEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"
        eOpposite="#//Room/slot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturer" lowerBound="1"
        upperBound="-1" eType="#//Teacher" eOpposite="#//Teacher/slot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" lowerBound="1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="week" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        eType="#//Course" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//ActivityEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivityEnum">
    <eLiterals name="Lecture"/>
    <eLiterals name="Exercise" value="1"/>
    <eLiterals name="Lab" value="2"/>
    <eLiterals name="Supervision" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DayEnum">
    <eLiterals name="Monday"/>
    <eLiterals name="Tuesday" value="1"/>
    <eLiterals name="Wednesday" value="2"/>
    <eLiterals name="Thurdsay" value="3"/>
    <eLiterals name="Friday" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CourseTimetable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="week" lowerBound="1" upperBound="52"
        eType="#//Week" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
