/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SrDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class UniversityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.University");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUniversityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cYearKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cYearAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cYearEIntParserRuleCall_4_0 = (RuleCall)cYearAssignment_4.eContents().get(0);
		private final Keyword cCampusKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCampiAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCampiCampusParserRuleCall_7_0 = (RuleCall)cCampiAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cCampiAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cCampiCampusParserRuleCall_8_1_0 = (RuleCall)cCampiAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cCourseKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cCourseAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cCourseCourseParserRuleCall_11_0 = (RuleCall)cCourseAssignment_11.eContents().get(0);
		private final Keyword cTeachersKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cLeftCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cTeachersAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cTeachersTeacherParserRuleCall_14_0 = (RuleCall)cTeachersAssignment_14.eContents().get(0);
		private final Group cGroup_15 = (Group)cGroup.eContents().get(15);
		private final Keyword cCommaKeyword_15_0 = (Keyword)cGroup_15.eContents().get(0);
		private final Assignment cTeachersAssignment_15_1 = (Assignment)cGroup_15.eContents().get(1);
		private final RuleCall cTeachersTeacherParserRuleCall_15_1_0 = (RuleCall)cTeachersAssignment_15_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		private final Keyword cRightCurlyBracketKeyword_17 = (Keyword)cGroup.eContents().get(17);
		
		//University returns University:
		//    'University'
		//    name=EString
		//    '{'
		//        'year' year=EInt
		//        'campus' '{' campi+=Campus ( "," campi+=Campus)* '}'
		//        'course' course=Course
		//        'teachers' '{' teachers+=Teacher ( "," teachers+=Teacher)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'University'
		//name=EString
		//'{'
		//    'year' year=EInt
		//    'campus' '{' campi+=Campus ( "," campi+=Campus)* '}'
		//    'course' course=Course
		//    'teachers' '{' teachers+=Teacher ( "," teachers+=Teacher)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'University'
		public Keyword getUniversityKeyword_0() { return cUniversityKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'year'
		public Keyword getYearKeyword_3() { return cYearKeyword_3; }
		
		//year=EInt
		public Assignment getYearAssignment_4() { return cYearAssignment_4; }
		
		//EInt
		public RuleCall getYearEIntParserRuleCall_4_0() { return cYearEIntParserRuleCall_4_0; }
		
		//'campus'
		public Keyword getCampusKeyword_5() { return cCampusKeyword_5; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }
		
		//campi+=Campus
		public Assignment getCampiAssignment_7() { return cCampiAssignment_7; }
		
		//Campus
		public RuleCall getCampiCampusParserRuleCall_7_0() { return cCampiCampusParserRuleCall_7_0; }
		
		//( "," campi+=Campus)*
		public Group getGroup_8() { return cGroup_8; }
		
		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }
		
		//campi+=Campus
		public Assignment getCampiAssignment_8_1() { return cCampiAssignment_8_1; }
		
		//Campus
		public RuleCall getCampiCampusParserRuleCall_8_1_0() { return cCampiCampusParserRuleCall_8_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'course'
		public Keyword getCourseKeyword_10() { return cCourseKeyword_10; }
		
		//course=Course
		public Assignment getCourseAssignment_11() { return cCourseAssignment_11; }
		
		//Course
		public RuleCall getCourseCourseParserRuleCall_11_0() { return cCourseCourseParserRuleCall_11_0; }
		
		//'teachers'
		public Keyword getTeachersKeyword_12() { return cTeachersKeyword_12; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_13() { return cLeftCurlyBracketKeyword_13; }
		
		//teachers+=Teacher
		public Assignment getTeachersAssignment_14() { return cTeachersAssignment_14; }
		
		//Teacher
		public RuleCall getTeachersTeacherParserRuleCall_14_0() { return cTeachersTeacherParserRuleCall_14_0; }
		
		//( "," teachers+=Teacher)*
		public Group getGroup_15() { return cGroup_15; }
		
		//","
		public Keyword getCommaKeyword_15_0() { return cCommaKeyword_15_0; }
		
		//teachers+=Teacher
		public Assignment getTeachersAssignment_15_1() { return cTeachersAssignment_15_1; }
		
		//Teacher
		public RuleCall getTeachersTeacherParserRuleCall_15_1_0() { return cTeachersTeacherParserRuleCall_15_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_17() { return cRightCurlyBracketKeyword_17; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class CampusElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.Campus");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCampusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBuildingsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cBuildingsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cBuildingsBuildingParserRuleCall_5_0 = (RuleCall)cBuildingsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cBuildingsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cBuildingsBuildingParserRuleCall_6_1_0 = (RuleCall)cBuildingsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Campus returns Campus:
		//    'Campus'
		//    name=EString
		//    '{'
		//        'buildings' '{' buildings+=Building ( "," buildings+=Building)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Campus'
		//name=EString
		//'{'
		//    'buildings' '{' buildings+=Building ( "," buildings+=Building)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Campus'
		public Keyword getCampusKeyword_0() { return cCampusKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'buildings'
		public Keyword getBuildingsKeyword_3() { return cBuildingsKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//buildings+=Building
		public Assignment getBuildingsAssignment_5() { return cBuildingsAssignment_5; }
		
		//Building
		public RuleCall getBuildingsBuildingParserRuleCall_5_0() { return cBuildingsBuildingParserRuleCall_5_0; }
		
		//( "," buildings+=Building)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//buildings+=Building
		public Assignment getBuildingsAssignment_6_1() { return cBuildingsAssignment_6_1; }
		
		//Building
		public RuleCall getBuildingsBuildingParserRuleCall_6_1_0() { return cBuildingsBuildingParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class CourseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.Course");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCourseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cCodeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cCodeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cCodeEStringParserRuleCall_4_0 = (RuleCall)cCodeAssignment_4.eContents().get(0);
		private final Keyword cCoordinatorKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cCoordinatorAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cCoordinatorTeacherCrossReference_6_0 = (CrossReference)cCoordinatorAssignment_6.eContents().get(0);
		private final RuleCall cCoordinatorTeacherEStringParserRuleCall_6_0_1 = (RuleCall)cCoordinatorTeacherCrossReference_6_0.eContents().get(1);
		private final Keyword cSchedulingrequirementsKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cSchedulingrequirementsAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSchedulingrequirementsSchedulingRequirementsParserRuleCall_8_0 = (RuleCall)cSchedulingrequirementsAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Course returns Course:
		//    'Course'
		//    name=EString
		//    '{'
		//        'code' code=EString
		//        'coordinator' coordinator=[Teacher|EString]
		//        'schedulingrequirements' schedulingrequirements=schedulingRequirements
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Course'
		//name=EString
		//'{'
		//    'code' code=EString
		//    'coordinator' coordinator=[Teacher|EString]
		//    'schedulingrequirements' schedulingrequirements=schedulingRequirements
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Course'
		public Keyword getCourseKeyword_0() { return cCourseKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'code'
		public Keyword getCodeKeyword_3() { return cCodeKeyword_3; }
		
		//code=EString
		public Assignment getCodeAssignment_4() { return cCodeAssignment_4; }
		
		//EString
		public RuleCall getCodeEStringParserRuleCall_4_0() { return cCodeEStringParserRuleCall_4_0; }
		
		//'coordinator'
		public Keyword getCoordinatorKeyword_5() { return cCoordinatorKeyword_5; }
		
		//coordinator=[Teacher|EString]
		public Assignment getCoordinatorAssignment_6() { return cCoordinatorAssignment_6; }
		
		//[Teacher|EString]
		public CrossReference getCoordinatorTeacherCrossReference_6_0() { return cCoordinatorTeacherCrossReference_6_0; }
		
		//EString
		public RuleCall getCoordinatorTeacherEStringParserRuleCall_6_0_1() { return cCoordinatorTeacherEStringParserRuleCall_6_0_1; }
		
		//'schedulingrequirements'
		public Keyword getSchedulingrequirementsKeyword_7() { return cSchedulingrequirementsKeyword_7; }
		
		//schedulingrequirements=schedulingRequirements
		public Assignment getSchedulingrequirementsAssignment_8() { return cSchedulingrequirementsAssignment_8; }
		
		//schedulingRequirements
		public RuleCall getSchedulingrequirementsSchedulingRequirementsParserRuleCall_8_0() { return cSchedulingrequirementsSchedulingRequirementsParserRuleCall_8_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class TeacherElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.Teacher");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTeacherKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Teacher returns Teacher:
		//    'Teacher'
		//    name=EString;
		@Override public ParserRule getRule() { return rule; }
		
		//'Teacher'
		//name=EString
		public Group getGroup() { return cGroup; }
		
		//'Teacher'
		public Keyword getTeacherKeyword_0() { return cTeacherKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class BuildingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.Building");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBuildingKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRoomsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRoomsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRoomsRoomParserRuleCall_5_0 = (RuleCall)cRoomsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cRoomsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cRoomsRoomParserRuleCall_6_1_0 = (RuleCall)cRoomsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Building returns Building:
		//    'Building'
		//    name=EString
		//    '{'
		//        'rooms' '{' rooms+=Room ( "," rooms+=Room)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Building'
		//name=EString
		//'{'
		//    'rooms' '{' rooms+=Room ( "," rooms+=Room)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Building'
		public Keyword getBuildingKeyword_0() { return cBuildingKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'rooms'
		public Keyword getRoomsKeyword_3() { return cRoomsKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//rooms+=Room
		public Assignment getRoomsAssignment_5() { return cRoomsAssignment_5; }
		
		//Room
		public RuleCall getRoomsRoomParserRuleCall_5_0() { return cRoomsRoomParserRuleCall_5_0; }
		
		//( "," rooms+=Room)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//rooms+=Room
		public Assignment getRoomsAssignment_6_1() { return cRoomsAssignment_6_1; }
		
		//Room
		public RuleCall getRoomsRoomParserRuleCall_6_1_0() { return cRoomsRoomParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class RoomElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.Room");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRoomKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cMazemapLinkKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMazemapLinkAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMazemapLinkEStringParserRuleCall_4_0 = (RuleCall)cMazemapLinkAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Room returns Room:
		//    'Room'
		//    name=EString
		//    '{'
		//        'mazemapLink' mazemapLink=EString
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Room'
		//name=EString
		//'{'
		//    'mazemapLink' mazemapLink=EString
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Room'
		public Keyword getRoomKeyword_0() { return cRoomKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'mazemapLink'
		public Keyword getMazemapLinkKeyword_3() { return cMazemapLinkKeyword_3; }
		
		//mazemapLink=EString
		public Assignment getMazemapLinkAssignment_4() { return cMazemapLinkAssignment_4; }
		
		//EString
		public RuleCall getMazemapLinkEStringParserRuleCall_4_0() { return cMazemapLinkEStringParserRuleCall_4_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class SchedulingRequirementsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.schedulingRequirements");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSchedulingRequirementsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSenderKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSenderAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSenderTeacherCrossReference_3_0 = (CrossReference)cSenderAssignment_3.eContents().get(0);
		private final RuleCall cSenderTeacherEStringParserRuleCall_3_0_1 = (RuleCall)cSenderTeacherCrossReference_3_0.eContents().get(1);
		private final Keyword cWeeksKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cWeeksAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cWeeksWeekParserRuleCall_6_0 = (RuleCall)cWeeksAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cWeeksAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cWeeksWeekParserRuleCall_7_1_0 = (RuleCall)cWeeksAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//schedulingRequirements returns schedulingRequirements:
		//    'SchedulingRequirements'
		//    '{'
		//        'sender' sender=[Teacher|EString]
		//        'weeks' '{' weeks+=Week ( "," weeks+=Week)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SchedulingRequirements'
		//'{'
		//    'sender' sender=[Teacher|EString]
		//    'weeks' '{' weeks+=Week ( "," weeks+=Week)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'SchedulingRequirements'
		public Keyword getSchedulingRequirementsKeyword_0() { return cSchedulingRequirementsKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'sender'
		public Keyword getSenderKeyword_2() { return cSenderKeyword_2; }
		
		//sender=[Teacher|EString]
		public Assignment getSenderAssignment_3() { return cSenderAssignment_3; }
		
		//[Teacher|EString]
		public CrossReference getSenderTeacherCrossReference_3_0() { return cSenderTeacherCrossReference_3_0; }
		
		//EString
		public RuleCall getSenderTeacherEStringParserRuleCall_3_0_1() { return cSenderTeacherEStringParserRuleCall_3_0_1; }
		
		//'weeks'
		public Keyword getWeeksKeyword_4() { return cWeeksKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//weeks+=Week
		public Assignment getWeeksAssignment_6() { return cWeeksAssignment_6; }
		
		//Week
		public RuleCall getWeeksWeekParserRuleCall_6_0() { return cWeeksWeekParserRuleCall_6_0; }
		
		//( "," weeks+=Week)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//weeks+=Week
		public Assignment getWeeksAssignment_7_1() { return cWeeksAssignment_7_1; }
		
		//Week
		public RuleCall getWeeksWeekParserRuleCall_7_1_0() { return cWeeksWeekParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class WeekElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.Week");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWeekKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cWeekNumberKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cWeekNumberAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cWeekNumberEIntParserRuleCall_3_0 = (RuleCall)cWeekNumberAssignment_3.eContents().get(0);
		private final Keyword cSlotRequirementsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cSlotRequirementsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cSlotRequirementsSlotRequirementParserRuleCall_6_0 = (RuleCall)cSlotRequirementsAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cSlotRequirementsAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cSlotRequirementsSlotRequirementParserRuleCall_7_1_0 = (RuleCall)cSlotRequirementsAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Week returns Week:
		//    'Week'
		//    '{'
		//        'weekNumber' weekNumber=EInt
		//        'slotRequirements' '{' slotRequirements+=SlotRequirement ( "," slotRequirements+=SlotRequirement)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Week'
		//'{'
		//    'weekNumber' weekNumber=EInt
		//    'slotRequirements' '{' slotRequirements+=SlotRequirement ( "," slotRequirements+=SlotRequirement)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Week'
		public Keyword getWeekKeyword_0() { return cWeekKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'weekNumber'
		public Keyword getWeekNumberKeyword_2() { return cWeekNumberKeyword_2; }
		
		//weekNumber=EInt
		public Assignment getWeekNumberAssignment_3() { return cWeekNumberAssignment_3; }
		
		//EInt
		public RuleCall getWeekNumberEIntParserRuleCall_3_0() { return cWeekNumberEIntParserRuleCall_3_0; }
		
		//'slotRequirements'
		public Keyword getSlotRequirementsKeyword_4() { return cSlotRequirementsKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//slotRequirements+=SlotRequirement
		public Assignment getSlotRequirementsAssignment_6() { return cSlotRequirementsAssignment_6; }
		
		//SlotRequirement
		public RuleCall getSlotRequirementsSlotRequirementParserRuleCall_6_0() { return cSlotRequirementsSlotRequirementParserRuleCall_6_0; }
		
		//( "," slotRequirements+=SlotRequirement)*
		public Group getGroup_7() { return cGroup_7; }
		
		//","
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//slotRequirements+=SlotRequirement
		public Assignment getSlotRequirementsAssignment_7_1() { return cSlotRequirementsAssignment_7_1; }
		
		//SlotRequirement
		public RuleCall getSlotRequirementsSlotRequirementParserRuleCall_7_1_0() { return cSlotRequirementsSlotRequirementParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class SlotRequirementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.SlotRequirement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSlotRequirementKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cActivityTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActivityTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActivityTypeActivityTypeEnumRuleCall_3_0 = (RuleCall)cActivityTypeAssignment_3.eContents().get(0);
		private final Keyword cDurationKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cDurationAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cDurationEIntParserRuleCall_5_0 = (RuleCall)cDurationAssignment_5.eContents().get(0);
		private final Keyword cExpectedStudentsKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cExpectedStudentsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cExpectedStudentsEIntParserRuleCall_7_0 = (RuleCall)cExpectedStudentsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cRequiredPersonalKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cRequiredPersonalAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final CrossReference cRequiredPersonalTeacherCrossReference_8_2_0 = (CrossReference)cRequiredPersonalAssignment_8_2.eContents().get(0);
		private final RuleCall cRequiredPersonalTeacherEStringParserRuleCall_8_2_0_1 = (RuleCall)cRequiredPersonalTeacherCrossReference_8_2_0.eContents().get(1);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cRequiredPersonalAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final CrossReference cRequiredPersonalTeacherCrossReference_8_3_1_0 = (CrossReference)cRequiredPersonalAssignment_8_3_1.eContents().get(0);
		private final RuleCall cRequiredPersonalTeacherEStringParserRuleCall_8_3_1_0_1 = (RuleCall)cRequiredPersonalTeacherCrossReference_8_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cRequiredRoomKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cRequiredRoomAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final CrossReference cRequiredRoomRoomCrossReference_9_1_0 = (CrossReference)cRequiredRoomAssignment_9_1.eContents().get(0);
		private final RuleCall cRequiredRoomRoomEStringParserRuleCall_9_1_0_1 = (RuleCall)cRequiredRoomRoomCrossReference_9_1_0.eContents().get(1);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cRequiredSameDaySlotsKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cRequiredSameDaySlotsAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final CrossReference cRequiredSameDaySlotsSlotRequirementCrossReference_10_2_0 = (CrossReference)cRequiredSameDaySlotsAssignment_10_2.eContents().get(0);
		private final RuleCall cRequiredSameDaySlotsSlotRequirementEStringParserRuleCall_10_2_0_1 = (RuleCall)cRequiredSameDaySlotsSlotRequirementCrossReference_10_2_0.eContents().get(1);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cRequiredSameDaySlotsAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final CrossReference cRequiredSameDaySlotsSlotRequirementCrossReference_10_3_1_0 = (CrossReference)cRequiredSameDaySlotsAssignment_10_3_1.eContents().get(0);
		private final RuleCall cRequiredSameDaySlotsSlotRequirementEStringParserRuleCall_10_3_1_0_1 = (RuleCall)cRequiredSameDaySlotsSlotRequirementCrossReference_10_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//SlotRequirement returns SlotRequirement:
		//    'SlotRequirement'
		//    '{'
		//        'activityType' activityType=ActivityType
		//        'duration' duration=EInt
		//        'expectedStudents' expectedStudents=EInt
		//        ('requiredPersonal' '(' requiredPersonal+=[Teacher|EString] ( "," requiredPersonal+=[Teacher|EString])* ')' )?
		//        ('requiredRoom' requiredRoom=[Room|EString])?
		//        ('requiredSameDaySlots' '(' requiredSameDaySlots+=[SlotRequirement|EString] ( "," requiredSameDaySlots+=[SlotRequirement|EString])* ')' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'SlotRequirement'
		//'{'
		//    'activityType' activityType=ActivityType
		//    'duration' duration=EInt
		//    'expectedStudents' expectedStudents=EInt
		//    ('requiredPersonal' '(' requiredPersonal+=[Teacher|EString] ( "," requiredPersonal+=[Teacher|EString])* ')' )?
		//    ('requiredRoom' requiredRoom=[Room|EString])?
		//    ('requiredSameDaySlots' '(' requiredSameDaySlots+=[SlotRequirement|EString] ( "," requiredSameDaySlots+=[SlotRequirement|EString])* ')' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'SlotRequirement'
		public Keyword getSlotRequirementKeyword_0() { return cSlotRequirementKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'activityType'
		public Keyword getActivityTypeKeyword_2() { return cActivityTypeKeyword_2; }
		
		//activityType=ActivityType
		public Assignment getActivityTypeAssignment_3() { return cActivityTypeAssignment_3; }
		
		//ActivityType
		public RuleCall getActivityTypeActivityTypeEnumRuleCall_3_0() { return cActivityTypeActivityTypeEnumRuleCall_3_0; }
		
		//'duration'
		public Keyword getDurationKeyword_4() { return cDurationKeyword_4; }
		
		//duration=EInt
		public Assignment getDurationAssignment_5() { return cDurationAssignment_5; }
		
		//EInt
		public RuleCall getDurationEIntParserRuleCall_5_0() { return cDurationEIntParserRuleCall_5_0; }
		
		//'expectedStudents'
		public Keyword getExpectedStudentsKeyword_6() { return cExpectedStudentsKeyword_6; }
		
		//expectedStudents=EInt
		public Assignment getExpectedStudentsAssignment_7() { return cExpectedStudentsAssignment_7; }
		
		//EInt
		public RuleCall getExpectedStudentsEIntParserRuleCall_7_0() { return cExpectedStudentsEIntParserRuleCall_7_0; }
		
		//('requiredPersonal' '(' requiredPersonal+=[Teacher|EString] ( "," requiredPersonal+=[Teacher|EString])* ')' )?
		public Group getGroup_8() { return cGroup_8; }
		
		//'requiredPersonal'
		public Keyword getRequiredPersonalKeyword_8_0() { return cRequiredPersonalKeyword_8_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_8_1() { return cLeftParenthesisKeyword_8_1; }
		
		//requiredPersonal+=[Teacher|EString]
		public Assignment getRequiredPersonalAssignment_8_2() { return cRequiredPersonalAssignment_8_2; }
		
		//[Teacher|EString]
		public CrossReference getRequiredPersonalTeacherCrossReference_8_2_0() { return cRequiredPersonalTeacherCrossReference_8_2_0; }
		
		//EString
		public RuleCall getRequiredPersonalTeacherEStringParserRuleCall_8_2_0_1() { return cRequiredPersonalTeacherEStringParserRuleCall_8_2_0_1; }
		
		//( "," requiredPersonal+=[Teacher|EString])*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//requiredPersonal+=[Teacher|EString]
		public Assignment getRequiredPersonalAssignment_8_3_1() { return cRequiredPersonalAssignment_8_3_1; }
		
		//[Teacher|EString]
		public CrossReference getRequiredPersonalTeacherCrossReference_8_3_1_0() { return cRequiredPersonalTeacherCrossReference_8_3_1_0; }
		
		//EString
		public RuleCall getRequiredPersonalTeacherEStringParserRuleCall_8_3_1_0_1() { return cRequiredPersonalTeacherEStringParserRuleCall_8_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8_4() { return cRightParenthesisKeyword_8_4; }
		
		//('requiredRoom' requiredRoom=[Room|EString])?
		public Group getGroup_9() { return cGroup_9; }
		
		//'requiredRoom'
		public Keyword getRequiredRoomKeyword_9_0() { return cRequiredRoomKeyword_9_0; }
		
		//requiredRoom=[Room|EString]
		public Assignment getRequiredRoomAssignment_9_1() { return cRequiredRoomAssignment_9_1; }
		
		//[Room|EString]
		public CrossReference getRequiredRoomRoomCrossReference_9_1_0() { return cRequiredRoomRoomCrossReference_9_1_0; }
		
		//EString
		public RuleCall getRequiredRoomRoomEStringParserRuleCall_9_1_0_1() { return cRequiredRoomRoomEStringParserRuleCall_9_1_0_1; }
		
		//('requiredSameDaySlots' '(' requiredSameDaySlots+=[SlotRequirement|EString] ( "," requiredSameDaySlots+=[SlotRequirement|EString])* ')' )?
		public Group getGroup_10() { return cGroup_10; }
		
		//'requiredSameDaySlots'
		public Keyword getRequiredSameDaySlotsKeyword_10_0() { return cRequiredSameDaySlotsKeyword_10_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_10_1() { return cLeftParenthesisKeyword_10_1; }
		
		//requiredSameDaySlots+=[SlotRequirement|EString]
		public Assignment getRequiredSameDaySlotsAssignment_10_2() { return cRequiredSameDaySlotsAssignment_10_2; }
		
		//[SlotRequirement|EString]
		public CrossReference getRequiredSameDaySlotsSlotRequirementCrossReference_10_2_0() { return cRequiredSameDaySlotsSlotRequirementCrossReference_10_2_0; }
		
		//EString
		public RuleCall getRequiredSameDaySlotsSlotRequirementEStringParserRuleCall_10_2_0_1() { return cRequiredSameDaySlotsSlotRequirementEStringParserRuleCall_10_2_0_1; }
		
		//( "," requiredSameDaySlots+=[SlotRequirement|EString])*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//requiredSameDaySlots+=[SlotRequirement|EString]
		public Assignment getRequiredSameDaySlotsAssignment_10_3_1() { return cRequiredSameDaySlotsAssignment_10_3_1; }
		
		//[SlotRequirement|EString]
		public CrossReference getRequiredSameDaySlotsSlotRequirementCrossReference_10_3_1_0() { return cRequiredSameDaySlotsSlotRequirementCrossReference_10_3_1_0; }
		
		//EString
		public RuleCall getRequiredSameDaySlotsSlotRequirementEStringParserRuleCall_10_3_1_0_1() { return cRequiredSameDaySlotsSlotRequirementEStringParserRuleCall_10_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_10_4() { return cRightParenthesisKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	
	public class ActivityTypeElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl.ActivityType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLECTUREEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLECTURELECTUREKeyword_0_0 = (Keyword)cLECTUREEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cEXERCISEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cEXERCISEEXERCISEKeyword_1_0 = (Keyword)cEXERCISEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLABEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLABLABKeyword_2_0 = (Keyword)cLABEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cSUPERVISIONEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cSUPERVISIONSUPERVISIONKeyword_3_0 = (Keyword)cSUPERVISIONEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum ActivityType returns ActivityType:
		//                LECTURE = 'LECTURE' | EXERCISE = 'EXERCISE' | LAB = 'LAB' | SUPERVISION = 'SUPERVISION';
		public EnumRule getRule() { return rule; }
		
		//LECTURE = 'LECTURE' | EXERCISE = 'EXERCISE' | LAB = 'LAB' | SUPERVISION = 'SUPERVISION'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LECTURE = 'LECTURE'
		public EnumLiteralDeclaration getLECTUREEnumLiteralDeclaration_0() { return cLECTUREEnumLiteralDeclaration_0; }
		
		//'LECTURE'
		public Keyword getLECTURELECTUREKeyword_0_0() { return cLECTURELECTUREKeyword_0_0; }
		
		//EXERCISE = 'EXERCISE'
		public EnumLiteralDeclaration getEXERCISEEnumLiteralDeclaration_1() { return cEXERCISEEnumLiteralDeclaration_1; }
		
		//'EXERCISE'
		public Keyword getEXERCISEEXERCISEKeyword_1_0() { return cEXERCISEEXERCISEKeyword_1_0; }
		
		//LAB = 'LAB'
		public EnumLiteralDeclaration getLABEnumLiteralDeclaration_2() { return cLABEnumLiteralDeclaration_2; }
		
		//'LAB'
		public Keyword getLABLABKeyword_2_0() { return cLABLABKeyword_2_0; }
		
		//SUPERVISION = 'SUPERVISION'
		public EnumLiteralDeclaration getSUPERVISIONEnumLiteralDeclaration_3() { return cSUPERVISIONEnumLiteralDeclaration_3; }
		
		//'SUPERVISION'
		public Keyword getSUPERVISIONSUPERVISIONKeyword_3_0() { return cSUPERVISIONSUPERVISIONKeyword_3_0; }
	}
	
	private final UniversityElements pUniversity;
	private final EStringElements pEString;
	private final CampusElements pCampus;
	private final CourseElements pCourse;
	private final TeacherElements pTeacher;
	private final EIntElements pEInt;
	private final BuildingElements pBuilding;
	private final RoomElements pRoom;
	private final SchedulingRequirementsElements pSchedulingRequirements;
	private final WeekElements pWeek;
	private final SlotRequirementElements pSlotRequirement;
	private final ActivityTypeElements eActivityType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SrDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pUniversity = new UniversityElements();
		this.pEString = new EStringElements();
		this.pCampus = new CampusElements();
		this.pCourse = new CourseElements();
		this.pTeacher = new TeacherElements();
		this.pEInt = new EIntElements();
		this.pBuilding = new BuildingElements();
		this.pRoom = new RoomElements();
		this.pSchedulingRequirements = new SchedulingRequirementsElements();
		this.pWeek = new WeekElements();
		this.pSlotRequirement = new SlotRequirementElements();
		this.eActivityType = new ActivityTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//University returns University:
	//    'University'
	//    name=EString
	//    '{'
	//        'year' year=EInt
	//        'campus' '{' campi+=Campus ( "," campi+=Campus)* '}'
	//        'course' course=Course
	//        'teachers' '{' teachers+=Teacher ( "," teachers+=Teacher)* '}'
	//    '}';
	public UniversityElements getUniversityAccess() {
		return pUniversity;
	}
	
	public ParserRule getUniversityRule() {
		return getUniversityAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Campus returns Campus:
	//    'Campus'
	//    name=EString
	//    '{'
	//        'buildings' '{' buildings+=Building ( "," buildings+=Building)* '}'
	//    '}';
	public CampusElements getCampusAccess() {
		return pCampus;
	}
	
	public ParserRule getCampusRule() {
		return getCampusAccess().getRule();
	}
	
	//Course returns Course:
	//    'Course'
	//    name=EString
	//    '{'
	//        'code' code=EString
	//        'coordinator' coordinator=[Teacher|EString]
	//        'schedulingrequirements' schedulingrequirements=schedulingRequirements
	//    '}';
	public CourseElements getCourseAccess() {
		return pCourse;
	}
	
	public ParserRule getCourseRule() {
		return getCourseAccess().getRule();
	}
	
	//Teacher returns Teacher:
	//    'Teacher'
	//    name=EString;
	public TeacherElements getTeacherAccess() {
		return pTeacher;
	}
	
	public ParserRule getTeacherRule() {
		return getTeacherAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//Building returns Building:
	//    'Building'
	//    name=EString
	//    '{'
	//        'rooms' '{' rooms+=Room ( "," rooms+=Room)* '}'
	//    '}';
	public BuildingElements getBuildingAccess() {
		return pBuilding;
	}
	
	public ParserRule getBuildingRule() {
		return getBuildingAccess().getRule();
	}
	
	//Room returns Room:
	//    'Room'
	//    name=EString
	//    '{'
	//        'mazemapLink' mazemapLink=EString
	//    '}';
	public RoomElements getRoomAccess() {
		return pRoom;
	}
	
	public ParserRule getRoomRule() {
		return getRoomAccess().getRule();
	}
	
	//schedulingRequirements returns schedulingRequirements:
	//    'SchedulingRequirements'
	//    '{'
	//        'sender' sender=[Teacher|EString]
	//        'weeks' '{' weeks+=Week ( "," weeks+=Week)* '}'
	//    '}';
	public SchedulingRequirementsElements getSchedulingRequirementsAccess() {
		return pSchedulingRequirements;
	}
	
	public ParserRule getSchedulingRequirementsRule() {
		return getSchedulingRequirementsAccess().getRule();
	}
	
	//Week returns Week:
	//    'Week'
	//    '{'
	//        'weekNumber' weekNumber=EInt
	//        'slotRequirements' '{' slotRequirements+=SlotRequirement ( "," slotRequirements+=SlotRequirement)* '}'
	//    '}';
	public WeekElements getWeekAccess() {
		return pWeek;
	}
	
	public ParserRule getWeekRule() {
		return getWeekAccess().getRule();
	}
	
	//SlotRequirement returns SlotRequirement:
	//    'SlotRequirement'
	//    '{'
	//        'activityType' activityType=ActivityType
	//        'duration' duration=EInt
	//        'expectedStudents' expectedStudents=EInt
	//        ('requiredPersonal' '(' requiredPersonal+=[Teacher|EString] ( "," requiredPersonal+=[Teacher|EString])* ')' )?
	//        ('requiredRoom' requiredRoom=[Room|EString])?
	//        ('requiredSameDaySlots' '(' requiredSameDaySlots+=[SlotRequirement|EString] ( "," requiredSameDaySlots+=[SlotRequirement|EString])* ')' )?
	//    '}';
	public SlotRequirementElements getSlotRequirementAccess() {
		return pSlotRequirement;
	}
	
	public ParserRule getSlotRequirementRule() {
		return getSlotRequirementAccess().getRule();
	}
	
	//enum ActivityType returns ActivityType:
	//                LECTURE = 'LECTURE' | EXERCISE = 'EXERCISE' | LAB = 'LAB' | SUPERVISION = 'SUPERVISION';
	public ActivityTypeElements getActivityTypeAccess() {
		return eActivityType;
	}
	
	public EnumRule getActivityTypeRule() {
		return getActivityTypeAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
