/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext.ui.tests;

import com.google.inject.Injector;
import no.ntnu.tdt4250.group13.scheduling_requirements.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class SrDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDsl");
	}

}
