/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext.parser.antlr;

import com.google.inject.Inject;
import no.ntnu.tdt4250.group13.scheduling_requirements.xtext.parser.antlr.internal.InternalSrDslParser;
import no.ntnu.tdt4250.group13.scheduling_requirements.xtext.services.SrDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SrDslParser extends AbstractAntlrParser {

	@Inject
	private SrDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSrDslParser createParser(XtextTokenStream stream) {
		return new InternalSrDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "University";
	}

	public SrDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SrDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
