/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDslRuntimeModule;
import no.ntnu.tdt4250.group13.scheduling_requirements.xtext.SrDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class SrDslIdeSetup extends SrDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new SrDslRuntimeModule(), new SrDslIdeModule()));
	}
	
}
