/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class SrDslIdeModule extends AbstractSrDslIdeModule {
}
