/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SrDslStandaloneSetup extends SrDslStandaloneSetupGenerated {

	public static void doSetup() {
		new SrDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
