/*
 * generated by Xtext 2.31.0
 */
package no.ntnu.tdt4250.group13.scheduling_requirements.xtext;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SrDslRuntimeModule extends AbstractSrDslRuntimeModule {
}
